refact(dependencies): Pinned MarkItDown to 0.0.2
Downgraded version because pip install of the latest 0.1.3 failed with
ERROR: Cannot install markitdown because these package versions have conflicting dependencies. The conflict is caused by:
- magika 0.6.3 depends on onnxruntime>=1.17.0; python_version > "3.9"
- magika 0.6.2 depends on onnxruntime>=1.17.0; python_version > "3.9"
- magika 0.6.1 depends on onnxruntime>=1.17.0; python_version > "3.9"

The root cause seems to be the incompatibility of onnxruntime with Alpine linux distribution, on which zms-base image relies.