Revised DB connection handling
Added pool_pre_ping=True according to https://docs.sqlalchemy.org/en/14/core/pooling.html#pool-disconnects because of

sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server conn crashed?
SSL connection has been closed unexpectedly
Background on this error at: https://sqlalche.me/e/14/e3q8

Tries to fix https://github.com/idasm-unibe-ch/unibe-cmsapi/issues/3